# vim: ft=tmux
# osx clipboard
set-option -g default-command "$SHELL"

# italic support
set -as terminal-overrides ',xterm*:sitm=\E[3m'
# undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
# underscore colours - needs tmux-3.0
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# copy selected text to system clipboard in a nested tmux session
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

